name: PR Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    uses: ./.github/workflows/template_Build.yml
