name: template_Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: Show packages folder tree
        shell: cmd
        run: |
          cd
          tree /F 
          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload all zip assets
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Get-ChildItem -Path .\artifacts -Filter *.zip -Recurse | ForEach-Object {
            Write-Host "Uploading $($_.FullName)..."
            gh release upload "${{ inputs.tag_name }}" "$($_.FullName)" --repo $env:GITHUB_REPOSITORY
          }
