name: template_Build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # adjust as needed

      - name: Add GitHub NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore ./GenerativeWorldBuildingUtility.csproj

      - name: Build Release
        run: dotnet build ./GenerativeWorldBuildingUtility.csproj --configuration Release --no-restore
        working-directory: ${{ github.workspace }}

      - name: Build AdminOverride
        run: dotnet build ./GenerativeWorldBuildingUtility.csproj --configuration AdminOverride --no-restore
        working-directory: ${{ github.workspace }}

      - name: Build ReleaseFullSubscription
        run: dotnet build ./GenerativeWorldBuildingUtility.csproj --configuration ReleaseFullSubscription --no-restore
        working-directory: ${{ github.workspace }}

      - name: Build ReleaseLimitedSubscription
        run: dotnet build ./GenerativeWorldBuildingUtility.csproj --configuration ReleaseLimitedSubscription --no-restore
        working-directory: ${{ github.workspace }}

      - name: Zip all Publish variants
        shell: pwsh
        run: |
          # Make an output directory for zips
          New-Item -ItemType Directory -Force -Path ./PublishZips | Out-Null

          # Loop through each subfolder in Publish and zip it
          Get-ChildItem -Path ./Publish -Directory | ForEach-Object {
            $name = $_.Name
            $zipPath = "./PublishZips/$name.zip"

            Write-Host "Zipping $name to $zipPath"
            Compress-Archive -Path $_.FullName -DestinationPath $zipPath -Force
          }

      - name: Upload zipped variants as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PublishVariants
          path: ./PublishZips/*.zip

